alexndProject/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth.views import LoginView
from django.urls import path, include

from userextend.forms import AuthenticationLoginForm, SetPasswordCustomForm, PasswordResetCustomForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('category.urls')),
    path('', include('product.urls')),
    path('', include('userextend.urls')),
    path('', include('contact.urls')),
    path('login/', LoginView.as_view(authentication_form=AuthenticationLoginForm), name="login"),
    path("reset/<uidb64>/<token>/", views.PasswordResetConfirmView.as_view(form_class=SetPasswordCustomForm),
         name="password_reset_confirm"),
    path("password_reset/", views.PasswordResetView.as_view(form_class=PasswordResetCustomForm), name="password_reset"),
    path('', include('django.contrib.auth.urls')),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='homepage'),
    path('open-cart-view/', views.open_cart_view, name='open_cart_view'),
    path('checkout/', views.checkout_view, name='checkout')
]

category/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=400)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

product/models.py
from django.contrib.auth.models import User
from django.db import models

from category.models import Category


class Product(models.Model):
    stock_choices = (('yes', 'Yes'), ('no', 'No'))

    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=400, null=True, blank=True)
    active = models.BooleanField(default=True)
    price = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=True)
    is_stock = models.CharField(max_length=10, choices=stock_choices, null=True, blank=True)
    release = models.DateField(null=True, blank=True)
    quantity = models.IntegerField(null=True, blank=True)
    # email = models.EmailField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='media/', null=True, blank=True)

    def __str__(self):
        return self.name


class Cart(models.Model):
    STATUSES = (
        ('open', 'Open'),
        ('close', 'Close')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=25, choices=STATUSES)

    def __str__(self):
        return f'{self.status} cart of {self.user}'


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.quantity} x {self.product.name}'

    def get_total(self):
        return self.product.price * self.quantity

templates/base.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sticky-footer-navbar/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'css/sticky-footer-navbar.css' %}" rel="stylesheet">
</head>
<body class="d-flex flex-column h-100">

<header>
    {% include 'menu.html' %}
</header>
<main class="flex-shrink-0">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</main>
<footer class="footer mt-auto py-3 bg-dark">
    <div class="container">
        <span class="text-muted">
        <a href="https://www.linkedin.com/in/alexandru-oprea-1b83a11a2/" class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin"
                 viewBox="0 0 16 16"><path
                    d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
            </svg>
        </a>
        <a href="#" class="btn btn-light">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook"
                 viewBox="0 0 16 16">
  <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
</svg>
        </a>
            <a href="https://gitlab.com/alexnd22" class="btn btn-light">
           <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-git"
                viewBox="0 0 16 16">
  <path d="M15.698 7.287 8.712.302a1.03 1.03 0 0 0-1.457 0l-1.45 1.45 1.84 1.84a1.223 1.223 0 0 1 1.55 1.56l1.773 1.774a1.224 1.224 0 0 1 1.267 2.025 1.226 1.226 0 0 1-2.002-1.334L8.58 5.963v4.353a1.226 1.226 0 1 1-1.008-.036V5.887a1.226 1.226 0 0 1-.666-1.608L5.093 2.465l-4.79 4.79a1.03 1.03 0 0 0 0 1.457l6.986 6.986a1.03 1.03 0 0 0 1.457 0l6.953-6.953a1.031 1.031 0 0 0 0-1.457"/>
</svg>
        </a>
  <a href="#" class="btn btn-light">
       <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram"
            viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
</svg>
        </a>
            <a href="{% url 'contact-form' %}" class="btn btn-outline-light">Contact</a>
            <br><br>
            <p> 2022, developed by Alexandru Oprea</p>
        </span>

    </div>
</footer>


<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>


</body>
</html>

templates/menu.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark  bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'homepage' %}">
            <img src="{% static 'icons/diamond_white_24dp.svg' %}" alt="" width="30" height="30"
                 class="d-inline-block align-text-top">
            eShop Project
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        All categories
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in allcategories %}
                            <li><a class="dropdown-item"
                                   href="{% url 'products_per_category' category.id %}">{{ category.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>

                {% if request.user.is_authenticated %}
                    {% if request.user.is_superuser or perms.category.create_category or perms.category.view_category %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Configure categories
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                {% if perms.category.add_category %}
                                    <li><a class="dropdown-item" href="{% url 'create_category' %}">Create a new
                                        category</a>
                                    </li>
                                {% endif %}
                                {% if perms.category.view_category %}

                                    <li><a class="dropdown-item" href="{% url 'list_of_categories' %}">List of
                                        categories</a>
                                    </li>
                                {% endif %}
                            </ul>
                        </li>
                    {% endif %}
                    {% if request.user.is_superuser or perms.product.create_product or perms.product.view_product %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Configure products
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">

                                {% if perms.product.create_product %}
                                    <li><a class="dropdown-item" href="{% url 'create_product' %}">Create a new
                                        product</a>
                                    </li>
                                {% endif %}

                                {% if perms.product.view_product %}
                                    <li><a class="dropdown-item" href="{% url 'list_of_products' %}">List of
                                        products</a>
                                    </li>
                                {% endif %}

                            </ul>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>

            {% if request.user.is_authenticated %}
                <div class="dropdown text-light">
                    <button class="dropdown-toggle btn text-light" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'icons/shopping_cart_black_24dp.svg' %}">({{ cart_items_count }})
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">

                        <li><a class="dropdown-item" href="{% url 'open_cart_view' %}">
                            Cart Info
                        </a></li>
                    </ul>
                </div>

                <div class="dropdown text-light">
                    <button class="dropdown-toggle btn text-light" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'icons/person_black_24dp.svg' %}">{{ request.user }}
                    </button>

                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        <li><a href="{% url 'update_user' request.user.id %}" class="dropdown-item">My profile</a>
                        </li>
                        <li><a href="{% url 'logout' %}" class="dropdown-item">Logout</a>
                        </li>
                    </ul>
                </div>

            {% else %}
                <a href="{% url 'create_user' %}" class="btn btn-outline-warning">Sign up</a>&nbsp;&nbsp;
                <a href="{% url 'login' %}" class="btn btn-outline-light">Login</a>
            {% endif %}

        </div>
    </div>
</nav>